/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
 * Generated on: 30-Apr-2024 15:19:53
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2023b.app/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int BL = 51;
const int32_T B[51] = {
      -1980356,    -5883206,    -5476868,     7636913,    29097045,    37185433,
      16553627,   -13943763,   -16493644,    13068854,    29803078,      852182,
     -36234118,   -19154253,    37391879,    44570149,   -26329115,   -73519251,
      -2288662,   102602303,    58832654,  -127452644,  -176793715,   144208295,
     665770352,   923606056,   665770352,   144208295,  -176793715,  -127452644,
      58832654,   102602303,    -2288662,   -73519251,   -26329115,    44570149,
      37391879,   -19154253,   -36234118,      852182,    29803078,    13068854,
     -16493644,   -13943763,    16553627,    37185433,    29097045,     7636913,
      -5476868,    -5883206,    -1980356
};
